-- export-schema-ddl.sql
--
-- READ-ONLY. Builds a DDL snapshot of the "public" schema from the system
-- catalogs and returns it as a single text value (one row, one column).
-- It only calls SELECT and pg_get_* catalog functions; it changes nothing.
--
-- Usage: paste into the Supabase Dashboard SQL editor, run it, copy the single
-- `baseline_sql` cell, and save it as
-- supabase/migrations/<YYYYMMDDHHMMSS>_<name>.sql (the timestamp is the UTC
-- "Generated at" time; the CLI skips files without it). Save with LF line
-- endings and a final newline. Review it for secrets (function bodies
-- especially) before committing. See supabase/README.md.
--
-- Covered: tables, columns, defaults, constraints, indexes, functions,
-- triggers, event triggers whose function lives in public, RLS flags,
-- policies, and table/column/function privileges. The header reports counts
-- of object kinds this script does NOT cover; they must all be 0.

with
tbl as (
  select c.oid, c.relname::text as relname, c.relowner, c.relacl,
         c.relrowsecurity, c.relforcerowsecurity
  from pg_class c
  where c.relnamespace = 'public'::regnamespace
    and c.relkind in ('r', 'p')
),
fn as (
  select p.oid, p.proname::text as proname, p.proowner, p.proacl,
         pg_get_function_identity_arguments(p.oid) as args
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace
    and p.prokind = 'f'
),
parts (sec, k, sub, ddl) as (
  -- 0. Header
  select 0, '', 0, concat_ws(E'\n',
    '-- Baseline snapshot of the "public" schema.',
    '-- Generated from the live catalog by supabase/scripts/export-schema-ddl.sql (read-only).',
    '-- Server version: ' || current_setting('server_version'),
    '-- Generated at: ' || to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS') || ' UTC',
    '-- Objects in public NOT covered by the generator (all must be 0): '
      || 'views=' || (select count(*) from pg_class
                       where relnamespace = 'public'::regnamespace and relkind in ('v', 'm'))
      || ', sequences=' || (select count(*) from pg_class
                             where relnamespace = 'public'::regnamespace and relkind = 'S')
      || ', foreign_tables=' || (select count(*) from pg_class
                                  where relnamespace = 'public'::regnamespace and relkind = 'f')
      || ', types=' || (select count(*) from pg_type t
                         where t.typnamespace = 'public'::regnamespace
                           and t.typtype in ('e', 'c', 'd', 'r')
                           and not exists (select 1 from pg_class c where c.reltype = t.oid))
      || ', non_function_routines=' || (select count(*) from pg_proc
                                         where pronamespace = 'public'::regnamespace and prokind <> 'f'),
    '',
    'SET check_function_bodies = false;')

  -- Section headings
  union all
  select s.sec, '', -1, s.title
  from (values
    (1, '-- ===== Tables ====='),
    (2, '-- ===== Primary key, unique and check constraints ====='),
    (3, '-- ===== Foreign keys ====='),
    (4, '-- ===== Indexes (not backing a constraint) ====='),
    (5, '-- ===== Functions ====='),
    (6, '-- ===== Triggers ====='),
    (7, '-- ===== Event triggers (function in public) ====='),
    (8, '-- ===== Row level security ====='),
    (9, '-- ===== Policies ====='),
    (10, '-- ===== Table and column privileges ====='),
    (11, '-- ===== Function privileges =====')
  ) as s (sec, title)

  -- 1. Tables
  union all
  select 1, t.relname, 0,
    'CREATE TABLE public.' || quote_ident(t.relname) || E' (\n'
    || string_agg(
         '    ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
         || case
              when a.attgenerated = 's' then ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
              when a.attidentity = 'a' then ' GENERATED ALWAYS AS IDENTITY'
              when a.attidentity = 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
              when d.adbin is not null then ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
              else ''
            end
         || case when a.attnotnull then ' NOT NULL' else '' end,
         E',\n' order by a.attnum)
    || E'\n);\n'
    || 'ALTER TABLE public.' || quote_ident(t.relname)
    || ' OWNER TO ' || quote_ident(pg_get_userbyid(t.relowner)) || ';'
  from tbl t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = t.oid and d.adnum = a.attnum
  group by t.relname, t.relowner

  -- 2 and 3. Constraints (foreign keys last so referenced keys exist)
  union all
  select case when co.contype = 'f' then 3 else 2 end, t.relname,
    case co.contype when 'p' then 1 when 'u' then 2 when 'x' then 3 when 'c' then 4 else 5 end,
    'ALTER TABLE public.' || quote_ident(t.relname)
    || ' ADD CONSTRAINT ' || quote_ident(co.conname) || ' ' || pg_get_constraintdef(co.oid) || ';'
  from tbl t
  join pg_constraint co on co.conrelid = t.oid
  where co.contype in ('p', 'u', 'x', 'c', 'f')

  -- 4. Indexes that do not back a primary key, unique or exclusion constraint
  union all
  select 4, t.relname, 0, pg_get_indexdef(i.indexrelid) || ';'
  from tbl t
  join pg_index i on i.indrelid = t.oid
  where not exists (
    select 1 from pg_constraint co
    where co.conindid = i.indexrelid and co.conrelid = t.oid and co.contype in ('p', 'u', 'x')
  )

  -- 5. Functions
  union all
  select 5, f.proname, 0,
    rtrim(pg_get_functiondef(f.oid), E'\n') || E';\n'
    || 'ALTER FUNCTION public.' || quote_ident(f.proname) || '(' || f.args || ')'
    || ' OWNER TO ' || quote_ident(pg_get_userbyid(f.proowner)) || ';'
  from fn f

  -- 6. Triggers. pg_get_triggerdef omits the function's schema when it is on
  -- the session search_path, so the function name is always schema-qualified.
  union all
  select 6, t.relname, 0,
    regexp_replace(pg_get_triggerdef(tg.oid, false),
                   'EXECUTE FUNCTION [^(]+\(',
                   'EXECUTE FUNCTION ' || quote_ident(tn.nspname) || '.' || quote_ident(tp.proname) || '(')
    || ';'
    || case when tg.tgenabled = 'D'
            then E'\nALTER TABLE public.' || quote_ident(t.relname)
                 || ' DISABLE TRIGGER ' || quote_ident(tg.tgname) || ';'
            else '' end
  from tbl t
  join pg_trigger tg on tg.tgrelid = t.oid and not tg.tgisinternal
  join pg_proc tp on tp.oid = tg.tgfoid
  join pg_namespace tn on tn.oid = tp.pronamespace

  -- 7. Event triggers whose function is in public (platform ones are left out)
  union all
  select 7, e.evtname::text, 0,
    'CREATE EVENT TRIGGER ' || quote_ident(e.evtname) || ' ON ' || e.evtevent
    || case when e.evttags is not null
            then E'\n    WHEN TAG IN ('
                 || (select string_agg(quote_literal(tag), ', ') from unnest(e.evttags) as tag) || ')'
            else '' end
    || E'\n    EXECUTE FUNCTION public.' || quote_ident(p.proname) || '();'
    || case e.evtenabled
         when 'D' then E'\nALTER EVENT TRIGGER ' || quote_ident(e.evtname) || ' DISABLE;'
         when 'R' then E'\nALTER EVENT TRIGGER ' || quote_ident(e.evtname) || ' ENABLE REPLICA;'
         when 'A' then E'\nALTER EVENT TRIGGER ' || quote_ident(e.evtname) || ' ENABLE ALWAYS;'
         else '' end
    || E'\nALTER EVENT TRIGGER ' || quote_ident(e.evtname)
    || ' OWNER TO ' || quote_ident(pg_get_userbyid(e.evtowner)) || ';'
  from pg_event_trigger e
  join pg_proc p on p.oid = e.evtfoid
  where p.pronamespace = 'public'::regnamespace

  -- 8. Row level security flags
  union all
  select 8, t.relname, 0,
    'ALTER TABLE public.' || quote_ident(t.relname) || ' ENABLE ROW LEVEL SECURITY;'
    || case when t.relforcerowsecurity
            then E'\nALTER TABLE public.' || quote_ident(t.relname) || ' FORCE ROW LEVEL SECURITY;'
            else '' end
  from tbl t
  where t.relrowsecurity

  -- 9. Policies
  union all
  select 9, t.relname || '/' || pol.polname, 0,
    'CREATE POLICY ' || quote_ident(pol.polname) || ' ON public.' || quote_ident(t.relname)
    || ' AS ' || case when pol.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end
    || ' FOR ' || case pol.polcmd
                    when 'r' then 'SELECT' when 'a' then 'INSERT'
                    when 'w' then 'UPDATE' when 'd' then 'DELETE' else 'ALL' end
    || ' TO ' || (select string_agg(case when r = 0 then 'PUBLIC'
                                         else quote_ident(pg_get_userbyid(r)) end, ', '
                                    order by case when r = 0 then 'PUBLIC' else pg_get_userbyid(r)::text end)
                  from unnest(pol.polroles) as r)
    || coalesce(E'\n    USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')', '')
    || coalesce(E'\n    WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')', '')
    || ';'
  from tbl t
  join pg_policy pol on pol.polrelid = t.oid

  -- 10. Table privileges: reset the API roles, then grant exactly what exists
  union all
  select 10, t.relname, 0,
    'REVOKE ALL ON TABLE public.' || quote_ident(t.relname)
    || ' FROM PUBLIC, anon, authenticated, service_role;'
    || coalesce(E'\n' || (
         select string_agg('GRANT ' || x.privs || ' ON TABLE public.' || quote_ident(t.relname)
                           || ' TO ' || x.grantee || ';', E'\n' order by x.grantee)
         from (
           select case when g.grantee = 0 then 'PUBLIC'
                       else quote_ident(pg_get_userbyid(g.grantee)) end as grantee,
                  string_agg(g.privilege_type, ', ' order by g.privilege_type) as privs
           from aclexplode(coalesce(t.relacl, acldefault('r', t.relowner))) as g
           where g.grantee <> t.relowner
           group by g.grantee
         ) as x), '')
  from tbl t

  -- 10b. Column-level privileges, if any exist
  union all
  select 10, t.relname, 1,
    'GRANT ' || g.privilege_type || ' (' || quote_ident(a.attname) || ') ON TABLE public.'
    || quote_ident(t.relname) || ' TO '
    || case when g.grantee = 0 then 'PUBLIC' else quote_ident(pg_get_userbyid(g.grantee)) end || ';'
  from tbl t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
                     and a.attacl is not null
  cross join lateral aclexplode(a.attacl) as g

  -- 11. Function privileges: reset, then grant exactly what exists
  union all
  select 11, f.proname, 0,
    'REVOKE ALL ON FUNCTION public.' || quote_ident(f.proname) || '(' || f.args || ')'
    || ' FROM PUBLIC, anon, authenticated, service_role;'
    || coalesce(E'\n' || (
         select string_agg('GRANT EXECUTE ON FUNCTION public.' || quote_ident(f.proname)
                           || '(' || f.args || ') TO '
                           || case when g.grantee = 0 then 'PUBLIC'
                                   else quote_ident(pg_get_userbyid(g.grantee)) end || ';',
                           E'\n' order by g.grantee)
         from aclexplode(coalesce(f.proacl, acldefault('f', f.proowner))) as g
         where g.grantee <> f.proowner
       ), '')
  from fn f
)
select string_agg(ddl, E'\n\n' order by sec, k, sub, ddl) as baseline_sql
from parts;
